spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:D:/SPRING/KURS/todoapp/todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include=: '*'